dist: trusty
sudo: required
#language: generic
services: mysql

virtualenv:
  system_site_packages: true

python:
  - "2.7"
  
before_install:
  - sudo python test.py
  - sudo apt-get update
  - sudo python test.py
  - mysql --version
  - wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python_2.1.5-1ubuntu14.04_all.deb
  - wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-py3_2.1.5-1ubuntu14.04_all.deb
  - sudo dpkg -i *.deb
  - sudo apt-get install -f
#  - pip install mysql-connector
  - sudo python test.py
  - sudo find / -name connector
  - sudo python test.py
  
install:
    - mysql --version
    
# command to run tests
script: make test
