#dist: trusty
#sudo: required
#language: generic

services: mysql
    
before_install:
  - mysql --version
  - mysql -e 'create database mysite_db;
  
# command to install dependencies
install:
    - mysql --version
# command to run tests
script: make test
