dist: trusty
sudo: required
#language: generic
services: mysql

python:
  - "2.7"
  
before_install:
  - mysql --version
  - sudo pip install --allow-external mysql-connector-python mysql-connector-python b

install:
    - mysql --version
    - pip install mysql-python
    
# command to run tests
script: make test
