dist: trusty
sudo: required
#language: generic
services: mysql

python:
  - "2.7"
  
before_install:
  - sudo apt-get update
  - mysql --version
  - wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python_2.1.5-1ubuntu14.04_all.deb
  - sudo dpkg -i *.deb
install:
    - mysql --version
    
# command to run tests
script: make test
