dist: trusty
sudo: required
#language: generic
services: mysql

python:
  - "2.7"
  
before_install:
  - sudo apt-get update
  - mysql --version
  - pip install https://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.1.14.tar.gz

install:
    - mysql --version
    
# command to run tests
script: make test
