

#before_install:
#    -  sudo wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python_2.1.5-1ubuntu14.04_all.deb 
#    -  sudo dpkg -i *.deb





{
  "sudo": "required",
  "dist": "trusty",
  "language": "generic",
  "before_install": [
    "sudo apt-get install -y software-properties-common",
    "sudo apt-add-repository -y ppa:fkrull/deadsnakes-python2.7",
    "sudo apt-get update",
    "sudo apt-get -y install python2.7",
    "sudo apt-add-repository -y ppa:ansible/ansible",
    "sudo apt-get update",
    "sudo apt-get -y install ansible"
  ],
  "script": [
    "sudo ansible-playbook tests/test.yml -i tests/hosts --syntax-check",
    "sudo ansible-playbook tests/test.yml -i tests/hosts",
    "sudo ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1"
  ],
  "group": "stable",
  "os": "linux"
}

# command to install dependencies
install: "pip install -r requirements"
# command to run tests
script: make test
