dist: trusty
sudo: required
#language: generic

services: mysql
    
before_install:
  - mysql --version
  - mysql -e 'create database mysite_db;'
  - wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python_2.1.5-1ubuntu14.04_all.deb
  - dpkg -i *.deb
  
install:
    - mysql --version
    - pip install mysql-python
# command to run tests
script: make test
