

#before_install:
#    -  sudo wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python_2.1.5-1ubuntu14.04_all.deb 
#    -  sudo dpkg -i *.deb






sudo: required
dist: trusty
language: generic

services: 
    - mysql
    

before_install:
    - mysql -u root
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'


# command to install dependencies
install: "pip install -r requirements"
# command to run tests
script: make test
