dist: trusty
sudo: required
language: generic

services: 
    - mysql
    
before_install:
  - sudo apt-get update
  - mysql --version
  - sudo find / -name mysql
  - sudo mysql -u root --host=127.0.0.1
  - sudo mysqld restart
  - sudo mysql -u root --host=127.0.0.1 -e "CREATE DATABASE TEST_DB"
# command to install dependencies
install:
    - mysql --version
# command to run tests
script: make test
