#dist: trusty
#sudo: required
#language: generic

services: mysql
    
before_install:
  - mysql --version
  - mysql -e 'create database mysite_db;'
  
  
install:
    - mysql --version
    - pip install mysql-python --use-mirrors
# command to run tests
script: make test
