dist: trusty
sudo: required
#language: generic
services: mysql

virtualenv:
  system_site_packages: true

python:
  - "2.7"
  
before_install:
  - sudo find / -name connector
  
install:
    pip install -r requirements.txt
    
# command to run tests
script: make -C tests test
