dist: trusty
sudo: required
#language: generic
services: mysql

python:
  - "2.7"
  
before_install:
  - mysql --version
  - pip install mysql-connector-python --allow-external mysql-connector-python

install:
    - mysql --version
    
# command to run tests
script: make test
