dist: trusty
sudo: required
language: generic

services: 
    - mysql
    
before_install:
  - sudo apt-get update
  - mysql --version
 

# command to install dependencies
install:
    - mysql --version
# command to run tests
script: make test
