dist: trusty
sudo: required
#language: generic
services: mysql

python:
  - "2.7"
  
before_install:
  - mysql --version
  - sudo apt-get install python-connector

install:
    - mysql --version
    - pip install mysql-python
    
# command to run tests
script: make test
